### ISSUE TITLE
sp-i586 core and MiSTer open-source FPGA project

### ISSUE THREAD

**Issue by jan-kleks** [lmEshoo/sp-i586#1]
Hello,

I just wanted to let you know, just in case you might be interested, that people were considering some time ago using your core for [the MiSTer open-source retrocomputer/retroconsole FPGA project](https://github.com/MiSTer-devel/Main_MiSTer/wiki).

[Link to the discussion.](http://www.atari-forum.com/viewtopic.php?t=34176#p350850)

Regards

**Comment by lmEshoo** [comment]
@jan-kleks Thanks! Glad its gained some interest in the community. This was a research project during undergrad and we were able target it to run on Nexys4 Board. Unfortunately, it has not been maintained since we left it last, but we were able to complete our objective which was to build and run a linux kernel and run python (micropython).
